### ISSUE TITLE
Can't use recompile with "mix_project": true

### ISSUE THREAD

**Issue by cafrias** [smanolloff/SublimeLinter-contrib-elixirc#10]
Hello there!

I have two files in mi project:

``` elixir
# ./lib/identicon.ex

defmodule Identicon do
  def hash_input(input) do
    hex = :crypto.hash(:md5, input)
      |> :binary.bin_to_list()
    # I'm getting the error in the line below
    %Identicon.Image{hex: hex}
  end
end
```

``` elixir
# ./lib/image.ex

defmodule Identicon.Image do
  defstruct hex: nil, color: nil, grid: nil, pixel_map: nil
end
```

What happens here is the following:

- If I __don't use__ option `"mix_project: true"`, I get `Struct undefined` error from the linter in the line: `%Identicon.Image{hex: hex}`, although the app works perfectly when run using `iex -S mix`.
- Because of the error explained above, I've decided to set `"mix_project"` to `true`. It works smoothly, but when I try to use `recompile` command from `iex -S mix`, even if I change the files I get `:noop` as response, and it won't recompile anything. The only work around I've found is recompile module by module, for example: `r Identicon`

My question is: Why I'm not able to recompile if using `"mix_project"` option set to `true`? Is there any better approach to what I'm trying to do?

Thanks in advance!

**Comment by smanolloff** [comment]
Thanks for reporting this issue, I will give it a look later today.

**Comment by smanolloff** [comment]
I was unable to reproduce your issue -- recompile picks up changed files either way.

If I understand you correctly, your `recompile` from the iex console works as intended (i.e. compiles changed files) **only** if you have `mix_project` set to `false` in your configuration?
(Keep in mind that `r <module>` seems to force recompilation of that module even if it has no changes)

PS. which elixir/mix version do you use? Do you use elixir version managers? What does the command `which iex` return (assuming unix os)?

**Comment by cafrias** [comment]
Now everything is working as expected ... After rebooting (something I should have done before reporting the issue), anyways, if it's for help more information here we go:

- `which iex`: `/usr/local/bin/iex`
- OS: MacOS 10.12.2
- Mix version: 1.3.4
- Elixir version: 1.3.4
- SublimeText: version 3 build 3126

The issue happened when setting "mix_project" to "true" and trying to use `recompile` command from `iex -S mix` console.

I'll close this issue, if it happens to come back I'll let you know.

Thanks!
