### ISSUE TITLE
Problem with Elixir 1.3.x and Mix Project

### ISSUE THREAD

**Issue by nmqanh** [smanolloff/SublimeLinter-contrib-elixirc#7]
I am having this problem when running with Elixir 1.3.x and Mix Project running a default project created using `mix phoenix.new`

```
SublimeLinter: elixirc activated: /Users/anhnguyen/.kiex/elixirs/elixir-1.3.3/bin/elixir 
SublimeLinter: elixirc: auth_controller.ex ['/Users/anhnguyen/.kiex/elixirs/elixir-1.3.3/bin/elixir', '-S', 'mix', 'compile', '--warnings-as-errors', '--ignore-module-conflict'] 
SublimeLinter: elixirc output:
Could not find Hex, which is needed to build dependency :phoenix
Shall I install Hex? (if running non-interactively, use: "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :phoenix from MyProject.Mixfile 
```

I am using SublimeText 3 with Sublimelinter 3 and SublimeLinter-contrib-elixirc installed with following settings:

``` json
"SublimeLinter": {
    "linters": {
       "elixirc": {
          "chdir": "/Users/anhnguyen/Developer/my_project",
          "mix_project": true
       }
    }
 }
```

**Comment by smanolloff** [comment]
This looks like an issue outside of the linter -- as per the [official hex website](https://hex.pm/docs/usage), mix will automatically prompt you to install hex if needed. It looks like you might just need to install it. Compile from the command line and answer with `Y` when mix asks you to install hex:

``` bash
cd /Users/anhnguyen/Developer/my_project

/Users/anhnguyen/.kiex/elixirs/elixir-1.3.3/bin/elixir -S mix compile --warnings-as-errors --ignore-module-conflict
```

Alternatively, you can just install it manually:

``` bash
mix archive.install 'https://hex.pm/installs/hex.ez'
```

Let me know if this helps.

**Comment by nmqanh** [comment]
I tried that and it's strange that it succeeded in Terminal while sublime is still having above error:

``` bash
cd /Users/anhnguyen/Developer/my_project
 /Users/anhnguyen/.kiex/elixirs/elixir-1.3.3/bin/elixir -S mix compile --warnings-as-errors --ignore-module-conflict
Compiling 1 file (.ex)
Generated my_project app
```

I also tried to re-install hex like you mentioned (actually it was installed before in that folder so I can develop), but that problem still happens.

Thanks for your guide.

**Comment by smanolloff** [comment]
ok, so its something related to your env, as set up by `kiex` (you probably have a `source "$HOME/.kiex/scripts/kiex"` in your bash_profile or so. Sublime does not load those files).

Maybe we could solve that issue by adjusting the env vars properly. Can you provide the output of the following:

```
mix archive

env | grep -iE 'mix|elixir|iex|erl'
```

**Comment by nmqanh** [comment]
Here is it:

``` bash
mix archive
* hex
Archives installed at: /Users/anhnguyen/.kiex/mix/archives/elixir-1.3.3

env | grep -iE 'mix|elixir|iex|erl'
PATH=/Users/anhnguyen/.rvm/gems/ruby-2.3.0/bin:/Users/anhnguyen/.rvm/gems/ruby-2.3.0@global/bin:/Users/anhnguyen/.rvm/rubies/ruby-2.3.0/bin:/Users/anhnguyen/.nvm/versions/node/v4.4.7/bin:/Users/anhnguyen/.kiex/elixirs/elixir-1.3.3/bin:/Users/anhnguyen/.kiex/bin:/Users/anhnguyen/erlang/19.0/bin:/Users/anhnguyen/.kiex/elixirs/elixir-1.3.3/bin:/Users/anhnguyen/.kiex/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/mysql/bin:/Users/anhnguyen/.rvm/bin:/Users/anhnguyen/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/mysql/bin:/Users/anhnguyen/.rvm/bin:/Users/anhnguyen/anaconda/bin
_KERL_SAVED_REBAR_PLT_DIR=/Users/anhnguyen/erlang/19.0
MANPATH=/Users/anhnguyen/.nvm/versions/node/v4.4.7/share/man:/Users/anhnguyen/erlang/19.0/man:
REBAR_PLT_DIR=/Users/anhnguyen/erlang/19.0
ELIXIR_VERSION=1.3.3
MIX_ARCHIVES=/Users/anhnguyen/.kiex/mix/archives/elixir-1.3.3
_KERL_PATH_REMOVABLE=/Users/anhnguyen/erlang/19.0/bin
_KERL_MANPATH_REMOVABLE=/Users/anhnguyen/erlang/19.0/man
_KERL_ACTIVE_DIR=/Users/anhnguyen/erlang/19.0
```

**Comment by smanolloff** [comment]
Ok, it seems sublime not flexible at all when it comes to customizing its environment. Therefore, I have prepared a workaround for this linter, but before it gets released, I would ask you to please give it a try:
1. From sublime's command palette, choose "PackageResourceViewer: OpenResource" -> "SublimeLinter-contrib-elixirc" -> "linter.py" (you will need [this](https://packagecontrol.io/packages/PackageResourceViewer) package installed)
2. Replace the file's contents with [this](https://raw.githubusercontent.com/smanolloff/SublimeLinter-contrib-elixirc/customize_linter_command/linter.py)
3. Add the `prepend` configuration as described [here](https://github.com/smanolloff/SublimeLinter-contrib-elixirc/blob/customize_linter_command/README.md#example-2)

Then please let me know if the error still occurs.

**Comment by nmqanh** [comment]
@smanolloff Great thanks a lot, it's working fine now. It's just like you said, it's not flexible enough, later if we gonna upgrade elixir, we will need to modify settings again. But at least we can make it work now 💯

**Comment by smanolloff** [comment]
Yes... it is more of a workaround, than a fix. But it is the best I can come up with at this point.
And thank you for trying it out :beer:
